### ISSUE TITLE
No response from TV for authentication

### ISSUE THREAD

**Issue by salmosalar** [semool/service.auto3dmodesony#1]
I installed add-on and set the TV IP address, but when attempting the authentication step, there is nothing happenning. TV is not giving any code.
Model is XBR40LX900.

Any suggestion?

**Comment by semool** [comment]
When nothing happens your TV not respond to authentication Request. I think your Model is to old (its an 2010 model) and use another api for communication.
You can try open this url in a Browser: http://TVIP/sony/accessControl
It should report back: {"error":[501,"Not Implemented"]}
When nothing happens this addon will never work with your TV, sorry.
